/**
 * Hot mounting: materialize a skill-kind harness entry as a real cordis
 * plugin (v2 optional item, design.md §6) and load it into the live loader
 * tree — no process restart. The generated plugin registers a model-facing
 * tool that carries the skill's description, argument contract, and python
 * reference; the `skill` tool remains the way to actually execute it.
 *
 * Layout under `<baseDir>/evolve/mounted/`:
 *   index.json                    mount ledger (id -> path, restored at boot)
 *   <skillName>/package.json      plugin manifest (ESM, main index.js)
 *   <skillName>/index.js          generated plugin: registers one tool
 *
 * The generated plugin imports nothing outside node builtins, so the mount
 * directory needs no node_modules of its own.
 */
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Context } from "@deepseek-ai/cordis";
import type { HarnessEntry } from "./types.js";
import { skillNameOf } from "./skill.js";

export interface MountRecord {
	id: string;
	/** Loader entry id (the `evolve:<name>` key). */
	entryId: string;
	/** Absolute path of the generated plugin package. */
	path: string;
	/** Entry revision the mount was generated from. */
	version: number;
	mountedAt: string;
}

export interface MountLedger {
	mounted: MountRecord[];
}

export function mountedDir(baseDir: string): string {
	return join(baseDir, "evolve", "mounted");
}

export function ledgerPath(baseDir: string): string {
	return join(mountedDir(baseDir), "index.json");
}

export function loadLedger(baseDir: string): MountLedger {
	const path = ledgerPath(baseDir);
	if (!existsSync(path)) {
		return { mounted: [] };
	}
	try {
		const raw = JSON.parse(readFileSync(path, "utf8")) as Partial<MountLedger>;
		return { mounted: Array.isArray(raw.mounted) ? (raw.mounted as MountRecord[]) : [] };
	} catch {
		return { mounted: [] };
	}
}

export function saveLedger(baseDir: string, ledger: MountLedger): void {
	mkdirSync(mountedDir(baseDir), { recursive: true });
	writeFileSync(ledgerPath(baseDir), `${JSON.stringify(ledger, null, 2)}\n`, "utf8");
}

/** Generate the plugin package files for one skill entry; returns the package dir. */
export function renderMountPackage(baseDir: string, entry: HarnessEntry): string {
	const dir = join(mountedDir(baseDir), skillNameOf(entry.id));
	mkdirSync(dir, { recursive: true });
	const toolName = `skill_${skillNameOf(entry.id)}`;
	writeFileSync(
		join(dir, "package.json"),
		`{\n  "name": "evolve-skill-${skillNameOf(entry.id)}",\n  "version": "1.0.0",\n  "main": "index.js",\n  "type": "module"\n}\n`,
		"utf8",
	);
	writeFileSync(join(dir, "index.js"), renderPluginSource(toolName, entry), "utf8");
	return dir;
}

/** The generated plugin source: one tool registration, no external imports. */
export function renderPluginSource(toolName: string, entry: HarnessEntry): string {
	const description = `${oneLine(entry.title)}. ${oneLine(entry.content)}`.slice(0, 400);
	const parameters = renderParameters(entry);
	const reference = JSON.stringify(entry.reference ?? {}, null, 2);
	const entryId = JSON.stringify(entry.id);
	const entryVersion = JSON.stringify(entry.version);
	const entryTitle = JSON.stringify(oneLine(entry.title));
	const skillName = JSON.stringify(skillNameOf(entry.id));
	return `/**
 * Generated by dsh-continual-evolve mount (${entry.id} v${entry.version}).
 * Hot-mounted into the live loader tree; edit the harness entry and remount
 * to regenerate. Execute the skill through the \`skill\` tool — this plugin
 * exposes its contract to the model.
 */
export const name = "evolve-skill-${skillNameOf(entry.id)}";

// Cordis requires declared service access; without this, \`ctx.tools\` throws
// "cannot get property \\"tools\\" without inject".
export const inject = ["tools"];

export function apply(ctx) {
  ctx.tools.register({
    name: ${JSON.stringify(toolName)},
    description: ${JSON.stringify(description)},
    parameters: ${JSON.stringify(parameters, null, 2)},
    output: {
      // No \`required\` on the string property: the direct-register value-schema
      // path rejects it ("required is not supported on type string").
      schema: { type: "object", additionalProperties: false, properties: { text: { type: "string" } } },
      render: (_args, value) => [{ type: "text", text: value?.text ?? "" }],
    },
    execute: async (args) => ({
      text: "Mounted skill " + ${entryId} + " (v" + ${entryVersion} + ").\\n" +
        "Description: " + ${entryTitle} + "\\n" +
        "Argument contract: " + JSON.stringify(args ?? {}) + "\\n" +
        "Python reference: " + ${JSON.stringify(reference)} + "\\n" +
        "Execute via the \`skill\` tool (skill name " + ${skillName} + ").",
    }),
  });
}
`;
}

/**
 * Map a skill entry's arguments contract to the tool-parameter schema.
 * Requiredness goes in a root-level `required` array (valid JSON Schema):
 * the mounted plugin registers via raw `ctx.tools.register`, and dsh-llm
 * sends `parameters` verbatim to the API, which rejects per-property
 * `required: true` ("true is not of type array").
 */
export function renderParameters(entry: HarnessEntry): Record<string, unknown> {
	const contract = entry.arguments ?? {};
	const properties: Record<string, unknown> = {};
	const required: string[] = [];
	for (const [key, spec] of Object.entries(contract)) {
		const record = typeof spec === "object" && spec !== null && !Array.isArray(spec) ? (spec as Record<string, unknown>) : {};
		const type = typeof record["type"] === "string" ? record["type"] : "string";
		const description = typeof record["description"] === "string" ? record["description"] : key;
		properties[key] = { type, description };
		if (record["required"] === true) {
			required.push(key);
		}
	}
	return {
		type: "object",
		additionalProperties: false,
		properties,
		...(required.length > 0 ? { required } : {}),
	};
}

/**
 * Mount one skill entry into the live loader. Requires the `loader` service
 * (resolved lazily, see FAQ #1); without it the package is still written and
 * the ledger records the entry for the next boot.
 */
export async function mountSkill(ctx: Context, baseDir: string, entry: HarnessEntry): Promise<MountRecord> {
	// Guidance skills are SKILL.md documents with no python reference — there
	// is no function to mount as a tool; only executable skills can hot-mount.
	if (entry.skill_kind === "guidance" || Object.keys(entry.reference ?? {}).length === 0) {
		throw new Error(`skill ${entry.id} has no python reference (guidance skills cannot be mounted — load them with the skill tool instead)`);
	}
	const dir = renderMountPackage(baseDir, entry);
	const entryId = `evolve-mount-${skillNameOf(entry.id)}`;
	const loader = (ctx as unknown as { get(name: string): unknown }).get("loader") as LoaderLike | undefined;
	if (loader) {
		try {
			// EntryOptions: {id, name (module specifier), config, group, disabled, inject} —
			// `name` must resolve as an ES module: Node ESM does not support
			// directory imports, so point at the generated index.js explicitly.
			await loader.create({ id: entryId, name: join(dir, "index.js") });
		} catch (cause) {
			throw new Error(`hot mount failed: ${cause instanceof Error ? cause.message : String(cause)}`);
		}
	}
	const record: MountRecord = {
		id: entry.id,
		entryId,
		path: dir,
		version: entry.version,
		mountedAt: new Date().toISOString(),
	};
	const ledger = loadLedger(baseDir);
	ledger.mounted = [...ledger.mounted.filter((m) => m.id !== entry.id), record];
	saveLedger(baseDir, ledger);
	return record;
}

/** Unmount a skill entry: remove the loader entry and the generated package. */
export async function unmountSkill(ctx: Context, baseDir: string, id: string): Promise<MountRecord | undefined> {
	const ledger = loadLedger(baseDir);
	const record = ledger.mounted.find((m) => m.id === id);
	if (!record) {
		return undefined;
	}
	const loader = (ctx as unknown as { get(name: string): unknown }).get("loader") as LoaderLike | undefined;
	if (loader) {
		try {
			await loader.remove(record.entryId);
		} catch (cause) {
			throw new Error(`hot unmount failed: ${cause instanceof Error ? cause.message : String(cause)}`);
		}
	}
	if (existsSync(record.path)) {
		rmSync(record.path, { recursive: true, force: true });
	}
	ledger.mounted = ledger.mounted.filter((m) => m.id !== id);
	saveLedger(baseDir, ledger);
	return record;
}

/** Re-mount every ledger entry at plugin boot (restart persistence). */
export async function restoreMounted(ctx: Context, baseDir: string): Promise<void> {
	const ledger = loadLedger(baseDir);
	const loader = (ctx as unknown as { get(name: string): unknown }).get("loader") as LoaderLike | undefined;
	for (const record of ledger.mounted) {
		if (!existsSync(join(record.path, "index.js"))) {
			continue; // package was removed; ledger prunes on next unmount
		}
		if (!loader) {
			continue;
		}
		try {
			await loader.create({ id: record.entryId, name: join(record.path, "index.js") });
		} catch (cause) {
			ctx.logger("continual-evolve").warn(
				`mount restore failed for ${record.id}: ${cause instanceof Error ? cause.message : String(cause)}`,
			);
		}
	}
}

interface LoaderLike {
	create(options: { id: string; name: string }): Promise<string>;
	remove(id: string): Promise<void>;
}

function oneLine(text: string): string {
	return text.replace(/\s+/g, " ").trim();
}
